version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
#    environment:
#      - NODE_ENV=development
#      - PORT=3000
#    command: ./.docker/start.sh
#    depends_on:
#      - db
#    networks:
#      - app-network